// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// node_mse_vec_cpp
NumericVector node_mse_vec_cpp(NumericMatrix X, NumericMatrix K, double eps);
RcppExport SEXP _DROP_node_mse_vec_cpp(SEXP XSEXP, SEXP KSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(node_mse_vec_cpp(X, K, eps));
    return rcpp_result_gen;
END_RCPP
}
// update_k_cpp
List update_k_cpp(NumericMatrix X, NumericMatrix K, double lambda, double tol, int max_iter);
RcppExport SEXP _DROP_update_k_cpp(SEXP XSEXP, SEXP KSEXP, SEXP lambdaSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(update_k_cpp(X, K, lambda, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// calculate_ebic_cpp
List calculate_ebic_cpp(NumericMatrix K, NumericMatrix X, double gamma);
RcppExport SEXP _DROP_calculate_ebic_cpp(SEXP KSEXP, SEXP XSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_ebic_cpp(K, X, gamma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DROP_node_mse_vec_cpp", (DL_FUNC) &_DROP_node_mse_vec_cpp, 3},
    {"_DROP_update_k_cpp", (DL_FUNC) &_DROP_update_k_cpp, 5},
    {"_DROP_calculate_ebic_cpp", (DL_FUNC) &_DROP_calculate_ebic_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_DROP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
