#' Plot True Graph Structure from Simulation Results or Adjacency Matrix
#'
#' Visualize the true graph structure from a simulation experiment or directly
#' from an adjacency matrix. Takes either the output from \code{drop.simulate()},
#' the output from \code{drop.generator()}, or a binary adjacency matrix and 
#' creates a network plot.
#'
#' @param graph_input Either a list output from \code{drop.simulate()}, 
#'   a list output from \code{drop.generator()}, or a binary adjacency matrix 
#'   (n x n matrix with 0/1 values).
#' @param layout Character. Layout algorithm for graph. Options: "fr" 
#'   (Fruchterman-Reingold), "circle", "kk" (Kamada-Kawai), 
#'   "star", "grid", "spiral". Default is "auto" which chooses based on graph type
#'   (only works when graph_input is from drop.simulate() or drop.generator()).
#' @param vertex.size Numeric. Size of vertices. Default is 3.
#' @param vertex.color Character. Color of vertices. Default is "#1f77b4".
#' @param vertex.label Logical. Whether to show vertex labels. Default is FALSE.
#' @param edge.width Numeric. Width of edges. Default is 0.5.
#' @param edge.color Character. Color of edges. Default is "#FF7F50".
#' @param edge.alpha Numeric. Transparency of edges (0-1). Default is 0.6.
#' @param show.stats Logical. Whether to show graph statistics as subtitle. 
#'   Default is TRUE.
#' @param title Character. Custom title. If NULL, uses graph type (for simulation
#'   results) or "Graph Structure" (for matrix input). Default is NULL.
#' @param use.ggplot Logical. If TRUE, uses ggplot2 for plotting. If FALSE, 
#'   uses base igraph plotting. Default is TRUE.
#'
#' @return If use.ggplot=TRUE, returns a ggplot object. If use.ggplot=FALSE, 
#'   plots to current device and returns the igraph object invisibly.
#'
#' @details
#' The function accepts three types of input:
#' \enumerate{
#'   \item \strong{Simulation results}: Output from \code{drop.simulate()}
#'   \item \strong{Generator output}: Output from \code{drop.generator()}
#'   \item \strong{Adjacency matrix}: A binary matrix (n x n) with 1 indicating
#'         an edge between nodes and 0 indicating no edge
#' }
#' 
#' When using simulation results or generator output, the function automatically 
#' chooses an appropriate layout based on graph type:
#' \itemize{
#'   \item Band graphs: spiral layout
#'   \item Hub graphs: star layout centered on hubs
#'   \item Other graphs: Fruchterman-Reingold layout
#' }
#'
#' @examples
#' \dontrun{
#' # Method 1: From simulation results
#' result <- drop.simulate(
#'   n = 100, p = 10,
#'   graph_type = "hub",
#'   contamination_scenario = "clean",
#'   simulation_times = 10,
#'   methods = c("DROP", "HUGE_Glasso"),
#'   seed = 123
#' )
#' drop.plot(result)
#' 
#' # Method 2: From drop.generator output
#' data_gen <- drop.generator(
#'   graph_type = "hub",
#'   n = 100,
#'   p = 10,
#'   contamination_scenario = "clean",
#'   seed = 456
#' )
#' drop.plot(data_gen)
#' 
#' # Method 3: From adjacency matrix generated by drop.generator
#' data_gen2 <- drop.generator(
#'   graph_type = "band",
#'   n = 100,
#'   p = 10,
#'   contamination_scenario = "clean",
#'   seed = 789
#' )
#' adj_matrix <- (abs(data_gen2$omega) > 1e-10) * 1
#' diag(adj_matrix) <- 0
#' drop.plot(adj_matrix, layout = "spiral")
#' 
#' # Customize appearance
#' drop.plot(data_gen, 
#'           layout = "circle",
#'           vertex.size = 5,
#'           vertex.color = "red",
#'           edge.color = "gray",
#'           title = "My Custom Graph")
#' 
#' # Save to file
#' library(ggplot2)
#' p <- drop.plot(data_gen)
#' ggsave("true_graph.pdf", p, width = 8, height = 8)
#' }
#'
#' @export
drop.plot <- function(
    graph_input,
    layout = "auto",
    vertex.size = 3,
    vertex.color = "#1f77b4",
    vertex.label = FALSE,
    edge.width = 0.5,
    edge.color = "#FF7F50",
    edge.alpha = 0.6,
    show.stats = TRUE,
    title = NULL,
    use.ggplot = TRUE
) {
  
  # Determine input type and extract adjacency matrix
  is_simulation_result <- FALSE
  graph_type <- NULL
  p <- NULL
  
  if (is.matrix(graph_input) || is.data.frame(graph_input) || 
      inherits(graph_input, "Matrix")) {
    # Input is an adjacency matrix (including sparse matrices)
    adj_matrix <- as.matrix(graph_input)
    
    # Validate matrix
    if (nrow(adj_matrix) != ncol(adj_matrix)) {
      stop("Adjacency matrix must be square (n x n)")
    }
    
    # Check if binary (allow small tolerance for numerical errors)
    if (!all(adj_matrix %in% c(0, 1)) && 
        any(adj_matrix < -1e-10 | adj_matrix > 1 + 1e-10)) {
      warning("Input appears to be a precision/covariance matrix rather than a binary adjacency matrix. Converting: |x| > 1e-6 -> 1, else -> 0")
      adj_matrix <- (abs(adj_matrix) > 1e-6) * 1
    }
    
    # Ensure diagonal is zero and matrix is symmetric
    diag(adj_matrix) <- 0
    if (!isSymmetric(adj_matrix)) {
      warning("Adjacency matrix is not symmetric. Making it symmetric: (A + A^T) / 2")
      adj_matrix <- (adj_matrix + t(adj_matrix)) / 2
      adj_matrix <- (adj_matrix > 0.5) * 1
    }
    
    p <- nrow(adj_matrix)
    
  } else if (is.list(graph_input)) {
    # Check if input is from drop.simulate() or drop.generator()
    
    if (all(c("graph_info", "params") %in% names(graph_input))) {
      # Input is from drop.simulate()
      is_simulation_result <- TRUE
      
      # Extract graph information
      graph_info <- graph_input$graph_info
      params <- graph_input$params
      graph_type <- params$graph_type
      p <- params$p
      
      # Get adjacency matrix
      if (!is.null(graph_info$adjacency)) {
        adj_matrix <- graph_info$adjacency
      } else if (!is.null(graph_info$theta)) {
        # Convert theta (precision matrix) to adjacency (0/1)
        adj_matrix <- (abs(graph_info$theta) > 1e-10) * 1
        diag(adj_matrix) <- 0
      } else {
        stop("Could not find adjacency or theta matrix in graph_info")
      }
      
    } else if (all(c("omega", "X") %in% names(graph_input))) {
      # Input is from drop.generator()
      is_simulation_result <- TRUE
      
      # Extract graph type and dimension if available
      if (!is.null(graph_input$graph_type)) {
        graph_type <- graph_input$graph_type
      }
      p <- ncol(graph_input$X)
      
      # Get adjacency matrix from omega (precision matrix)
      adj_matrix <- (abs(graph_input$omega) > 1e-10) * 1
      diag(adj_matrix) <- 0
      
    } else {
      stop("If graph_input is a list, it must be either:\n",
           "  1. Output from drop.simulate() (with 'graph_info' and 'params'), or\n",
           "  2. Output from drop.generator() (with 'omega' and 'X')")
    }
    
  } else {
    stop("graph_input must be either:\n",
         "  1. A list returned from drop.simulate(),\n",
         "  2. A list returned from drop.generator(), or\n",
         "  3. An adjacency matrix (n x n matrix)")
  }
  
  # Check if igraph is available
  if (!requireNamespace("igraph", quietly = TRUE)) {
    stop("Package 'igraph' is required for plotting. Please install it.")
  }
  
  # Create igraph object
  g <- igraph::graph_from_adjacency_matrix(adj_matrix, mode = "undirected")
  n_vertices <- igraph::vcount(g)
  
  # Determine layout
  if (layout == "auto") {
    # Choose layout based on graph type (only available for simulation results)
    if (is_simulation_result && !is.null(graph_type)) {
      if (graph_type == "band") {
        layout <- "spiral"
      } else if (graph_type == "hub") {
        layout <- "star"
      } else {
        layout <- "fr"
      }
    } else {
      # Default to fr for matrix input
      layout <- "fr"
    }
  }
  
  # Compute layout
  if (layout == "spiral") {
    # Spiral layout for band graphs
    t <- seq(0, 4*pi, length.out = n_vertices)
    r <- t / (4*pi) * 2.5
    x_coords <- r * cos(t)
    y_coords <- r * sin(t)
    layout_mat <- cbind(x_coords, y_coords)
    
  } else if (layout == "fr") {
    layout_mat <- igraph::layout_with_fr(g, niter = 500)
    
  } else if (layout == "kk") {
    layout_mat <- igraph::layout_with_kk(g)
    
  } else if (layout == "circle") {
    layout_mat <- igraph::layout_in_circle(g)
    
  } else if (layout == "star") {
    # Star layout: put high-degree nodes in center
    degrees <- igraph::degree(g)
    if (max(degrees) > min(degrees)) {
      layout_mat <- igraph::layout_with_fr(g, niter = 500)
    } else {
      layout_mat <- igraph::layout_in_circle(g)
    }
    
  } else if (layout == "grid") {
    layout_mat <- igraph::layout_on_grid(g)
    
  } else {
    stop(sprintf("Unknown layout: %s. Use 'fr', 'kk', 'circle', 'star', 'grid', or 'spiral'", layout))
  }
  
  # Prepare title and subtitle
  if (is.null(title)) {
    if (is_simulation_result && !is.null(graph_type)) {
      title <- sprintf("True Graph Structure: %s", 
                       tools::toTitleCase(graph_type))
    } else {
      title <- "Graph Structure"
    }
  }
  
  subtitle <- NULL
  if (show.stats) {
    # Calculate statistics
    n_edges <- igraph::ecount(g)
    n_possible <- n_vertices * (n_vertices - 1) / 2
    sparsity <- 1-n_edges / n_possible
    
    if (is_simulation_result) {
      # Use graph_info if available for consistency
      if (!is.null(graph_input$graph_info$true_edges)) {
        n_edges <- graph_input$graph_info$true_edges
        n_possible <- graph_input$graph_info$total_edges
        sparsity <- graph_input$graph_info$true_sparsity
      }
    }
    
    subtitle <- sprintf("p = %d | Edges: %d / %d | Sparsity: %.2f%%",
                       n_vertices, n_edges, n_possible, 
                       sparsity * 100)
  }
  
  # Plot using ggplot2 or base igraph
  if (use.ggplot) {
    # Check if ggplot2 is available
    if (!requireNamespace("ggplot2", quietly = TRUE)) {
      warning("Package 'ggplot2' not available, using base plotting instead")
      use.ggplot <- FALSE
    }
  }
  
  if (use.ggplot) {
    # Prepare edge data
    edges <- igraph::as_edgelist(g, names = FALSE)
    if (nrow(edges) > 0) {
      edges_df <- data.frame(
        x1 = layout_mat[edges[, 1], 1],
        y1 = layout_mat[edges[, 1], 2],
        x2 = layout_mat[edges[, 2], 1],
        y2 = layout_mat[edges[, 2], 2]
      )
    } else {
      edges_df <- data.frame(x1 = numeric(0), y1 = numeric(0),
                             x2 = numeric(0), y2 = numeric(0))
    }
    
    # Prepare node data
    nodes_df <- data.frame(
      x = layout_mat[, 1],
      y = layout_mat[, 2],
      degree = igraph::degree(g)
    )
    
    # Create ggplot
    p <- ggplot2::ggplot() +
      ggplot2::geom_segment(
        data = edges_df, 
        ggplot2::aes_string(x = "x1", y = "y1", xend = "x2", yend = "y2"),
        color = edge.color, 
        linewidth = edge.width, 
        alpha = edge.alpha
      ) +
      ggplot2::geom_point(
        data = nodes_df, 
        ggplot2::aes_string(x = "x", y = "y"),
        color = vertex.color, 
        alpha = 0.8, 
        size = vertex.size
      ) +
      ggplot2::theme_void() +
      ggplot2::theme(
        plot.title = ggplot2::element_text(hjust = 0.5, size = 14, face = "bold"),
        plot.subtitle = ggplot2::element_text(hjust = 0.5, size = 10),
        plot.margin = ggplot2::margin(10, 10, 10, 10)
      )
    
    # Add title and subtitle
    if (!is.null(title)) {
      p <- p + ggplot2::ggtitle(title)
    }
    if (!is.null(subtitle)) {
      p <- p + ggplot2::labs(subtitle = subtitle)
    }
    
    # Add labels if requested
    if (vertex.label) {
      nodes_df$label <- seq_len(nrow(nodes_df))
      p <- p + ggplot2::geom_text(
        data = nodes_df,
        ggplot2::aes_string(x = "x", y = "y", label = "label"),
        size = 2,
        color = "black"
      )
    }
    
    return(p)
    
  } else {
    # Base igraph plotting
    if (!is.null(title)) {
      main_title <- title
      if (!is.null(subtitle)) {
        main_title <- paste0(title, "\n", subtitle)
      }
    } else {
      main_title <- subtitle
    }
    
    plot(g,
         layout = layout_mat,
         vertex.size = vertex.size * 2,
         vertex.color = vertex.color,
         vertex.label = if (vertex.label) igraph::V(g) else NA,
         vertex.label.cex = 0.6,
         vertex.label.color = "black",
         edge.width = edge.width,
         edge.color = edge.color,
         main = main_title,
         margin = 0)
    
    return(invisible(g))
  }
}
