#' Generate LaTeX Tables from DROP Simulation Results
#'
#' @description
#' This function reads simulation results from RDS or Excel files generated by DROP
#' and creates formatted LaTeX tables showing performance metrics (F1, MCC) with 
#' standard deviations across different contamination scenarios.
#'
#' @param file_path Character string (file path), list with 'summary' component, or data frame.
#'        Can be: (1) Path to RDS/Excel file, (2) Result object from drop.simulate()/drop.merge(),
#'        or (3) Summary data frame directly.
#' @param output_file Character. Path for the output LaTeX file. Default: "drop_tables.tex"
#' @param metrics Character vector. Metrics to include in the table. 
#'        Default: c("F1", "MCC"). Available options: "F1", "MCC", "Precision", "Recall", "Specificity", "Time", "Success Rate".
#'        You can select any combination, e.g., c("Precision", "Recall") or just "F1".
#' @param show_sd Logical. Whether to show standard deviations in parentheses. Default: TRUE
#' @param digits Integer. Number of decimal places to display. Default: 3
#' @param p_values Numeric vector. Which p values to generate tables for. 
#'        If NULL (default), uses all p values in the data.
#' @param scenarios Character vector. Which contamination scenarios to include.
#'        If NULL (default), uses all scenarios in the data.
#' @param landscape Logical. Whether to use landscape mode. Default: TRUE
#'
#' @return Invisibly returns the summary data frame used to generate tables.
#'
#' @details
#' The function expects the input file to contain a list with a 'summary' component,
#' as generated by drop.simulate() or drop.merge(). The summary should be a data frame
#' with columns including:
#' \itemize{
#'   \item method_name
#'   \item n (sample size)
#'   \item p (dimension)
#'   \item graph_type
#'   \item contamination_scenario
#'   \item F1_mean, F1_sd
#'   \item MCC_mean, MCC_sd
#'   \item Precision_mean, Precision_sd (optional)
#'   \item Recall_mean, Recall_sd (optional)
#'   \item Specificity_mean, Specificity_sd (optional)
#'   \item time_mean, time_sd (optional)
#'   \item success_rate (optional)
#' }
#'
#' @examples
#' \dontrun{
#' # Method 1: Generate tables from RDS file path
#' drop.latex("sim_p10.rds", output_file = "results.tex")
#' 
#' # Method 2: Read data first, then pass data frame
#' data <- readRDS("sim_p10.rds")
#' drop.latex(data)  # Pass the entire list
#' drop.latex(data$summary)  # Or pass the summary data frame directly
#' 
#' # Generate tables for specific scenarios
#' drop.latex("sim_p10.rds", 
#'            scenarios = c("clean", "cauchy"),
#'            metrics = c("F1", "MCC", "Precision"))
#' 
#' # Only Precision and Recall
#' drop.latex("sim_p10.rds",
#'            metrics = c("Precision", "Recall"))
#' 
#' # Include computation time with 2 decimal places
#' drop.latex("sim_p10.rds",
#'            metrics = c("F1", "MCC", "Time"),
#'            digits = 2)
#' 
#' # Read from Excel file
#' drop.latex("sim_p10.xlsx", output_file = "appendix.tex")
#' }
#'
#' @export
drop.latex <- function(file_path, 
                       output_file = "drop_tables.tex",
                       metrics = c("F1", "MCC"),
                       show_sd = TRUE,
                       digits = 3,
                       p_values = NULL,
                       scenarios = NULL,
                       landscape = TRUE) {
  
  # Determine input type and extract summary data
  simulation_times <- NULL  # Will try to extract from data
  
  if (is.character(file_path)) {
    # Input is a file path
    if (!file.exists(file_path)) {
      stop("File not found: ", file_path)
    }
    
    # Read data based on file extension
    file_ext <- tolower(tools::file_ext(file_path))
    
    if (file_ext == "rds") {
      data <- readRDS(file_path)
      if (!"summary" %in% names(data)) {
        stop("RDS file must contain a 'summary' component")
      }
      summary_data <- data$summary
      # Try to extract simulation_times from params or results
      if ("params" %in% names(data) && "simulation_times" %in% names(data$params)) {
        simulation_times <- data$params$simulation_times
      } else if ("results" %in% names(data) && "simulation_times" %in% names(data$results)) {
        simulation_times <- data$results$simulation_times[1]
      }
    } else if (file_ext %in% c("xlsx", "xls")) {
      if (!requireNamespace("readxl", quietly = TRUE)) {
        stop("Package 'readxl' is required to read Excel files. Please install it.")
      }
      # Read summary sheet
      summary_data <- readxl::read_excel(file_path, sheet = "summary")
    } else {
      stop("Unsupported file format. Please provide an RDS or Excel file.")
    }
    
  } else if (is.data.frame(file_path)) {
    # Input is a data frame - assume it's the summary data
    summary_data <- file_path
    
  } else if (is.list(file_path)) {
    # Input is a list - check if it has summary component
    if ("summary" %in% names(file_path)) {
      summary_data <- file_path$summary
      # Try to extract simulation_times from params or results
      if ("params" %in% names(file_path) && "simulation_times" %in% names(file_path$params)) {
        simulation_times <- file_path$params$simulation_times
      } else if ("results" %in% names(file_path) && "simulation_times" %in% names(file_path$results)) {
        simulation_times <- file_path$results$simulation_times[1]
      }
    } else {
      stop("List input must contain a 'summary' component")
    }
    
  } else {
    stop("Input must be a file path (character), data frame, or list with 'summary' component")
  }
  
  # Validate summary data
  required_cols <- c("method_name", "n", "p", "graph_type", "contamination_scenario")
  missing_cols <- setdiff(required_cols, names(summary_data))
  if (length(missing_cols) > 0) {
    stop("Summary data missing required columns: ", paste(missing_cols, collapse = ", "))
  }
  
  # Get unique p values and scenarios
  if (is.null(p_values)) {
    p_values <- sort(unique(summary_data$p))
  }
  if (is.null(scenarios)) {
    scenarios <- unique(summary_data$contamination_scenario)
  }
  
  # Open output file
  sink(output_file)
  on.exit(sink())
  
  # Generate tables for each p value and scenario
  for (p_val in p_values) {
    for (scenario in scenarios) {
      .generate_single_table(
        summary_data = summary_data,
        p_val = p_val,
        scenario = scenario,
        metrics = metrics,
        show_sd = show_sd,
        digits = digits,
        landscape = landscape,
        simulation_times = simulation_times
      )
    }
  }
  
  cat("\n% End of DROP LaTeX tables\n")
  
  message("LaTeX tables generated in: ", output_file)
  invisible(summary_data)
}


#' Internal function to generate a single LaTeX table
#' @keywords internal
.generate_single_table <- function(summary_data, p_val, scenario, 
                                   metrics, show_sd, digits, landscape,
                                   simulation_times = NULL) {
  
  # Filter data
  df <- summary_data[summary_data$p == p_val & 
                      summary_data$contamination_scenario == scenario, ]
  
  if (nrow(df) == 0) {
    warning("No data found for p=", p_val, ", scenario=", scenario)
    return(invisible(NULL))
  }
  
  # Method mapping
  method_mapping <- c(
    "DROP" = "DROP",
    "HUGE_Glasso" = "Glasso",
    "HUGE_MB" = "MB",
    "NPN" = "NPN",
    "Scaled_Lasso" = "Scaled Lasso",
    "SCAD" = "SCAD",
    "MCP" = "MCP",
    "CLIME" = "CLIME",
    "TIGER" = "TIGER",
    "Kendall" = "Kendall",
    "Spearman" = "Spearman",
    "SCIO" = "SCIO"
  )
  
  # Graph type mapping
  graph_mapping <- c(
    "band" = "Band",
    "hub" = "Hub",
    "cluster" = "Cluster",
    "random" = "Random",
    "scale-free" = "Scale-Free"
  )
  
  # Get available methods and graphs from data
  available_methods <- unique(df$method_name)
  method_order <- method_mapping[method_mapping %in% 
                                   sapply(available_methods, function(x) method_mapping[x])]
  if (length(method_order) == 0) {
    method_order <- available_methods  # Use original names if no mapping
  }
  
  available_graphs <- unique(df$graph_type)
  graph_order <- graph_mapping[graph_mapping %in% 
                                 sapply(available_graphs, function(x) graph_mapping[x])]
  if (length(graph_order) == 0) {
    graph_order <- available_graphs  # Use original names if no mapping
  }
  
  # Get sample sizes
  n_order <- sort(unique(df$n))
  
  # Number of metrics
  n_metrics <- length(metrics)
  n_graphs <- length(graph_order)
  
  # Create caption and label
  # Generate scenario description based on contamination type
  if (tolower(scenario) == "clean") {
    scenario_desc <- "Clean data"
  } else if (tolower(scenario) == "cauchy") {
    scenario_desc <- "Cauchy contamination"
  } else if (tolower(scenario) == "leverage") {
    scenario_desc <- "Leverage contamination"
  } else {
    # Fallback for other scenarios
    scenario_desc <- gsub("_", " ", scenario)
    scenario_desc <- paste0(toupper(substring(scenario_desc, 1, 1)), 
                           substring(scenario_desc, 2))
    scenario_desc <- paste0(scenario_desc, " contamination")
  }
  
  # Add replicates information if available
  if (!is.null(simulation_times) && !is.na(simulation_times)) {
    scenario_desc <- sprintf("%s (mean over %d replicates)", scenario_desc, simulation_times)
  }
  
  # Generate metric names for caption
  if (length(metrics) == 1) {
    metric_names <- metrics[1]
  } else if (length(metrics) == 2) {
    metric_names <- paste(metrics[1], "and", metrics[2])
  } else {
    metric_names <- paste(paste(metrics[-length(metrics)], collapse = ", "), 
                          "and", metrics[length(metrics)])
  }
  
  caption <- sprintf("%s scores for $p=%d$: %s", 
                     metric_names, p_val, scenario_desc)
  label <- sprintf("tab:p%d_%s", p_val, scenario)
  
  # Start table
  if (landscape) {
    cat("\\begin{landscape}\n")
  }
  cat("\\begin{table}[!htbp]\n")
  cat("\\centering\n")
  cat(sprintf("\\caption{%s}\n", caption))
  cat(sprintf("\\label{%s}\n", label))
  cat("\\footnotesize\n")
  
  # Build column specification
  col_spec <- "ll"  # n and Method columns
  for (i in 1:n_metrics) {
    col_spec <- paste0(col_spec, paste(rep("c", n_graphs), collapse = ""))
    if (i < n_metrics) {
      col_spec <- paste0(col_spec, "c")  # separator column
    }
  }
  cat(sprintf("\\begin{tabular}{@{}%s@{}}\n", col_spec))
  cat("\\toprule\n")
  
  # Header row with metric names
  header_line <- "& & "  # Skip n and Method columns
  cmidrule_line <- ""
  col_counter <- 3  # Start after n and Method columns
  
  for (i in 1:n_metrics) {
    metric_display <- metrics[i]
    # Add (SD) suffix except for Success Rate which doesn't have SD
    if (show_sd && metrics[i] != "Success Rate") {
      metric_display <- paste0(metric_display, " (SD)")
    }
    header_line <- paste0(header_line, sprintf("\\multicolumn{%d}{c}{%s}", 
                                                n_graphs, metric_display))
    cmidrule_line <- paste0(cmidrule_line, 
                           sprintf("\\cmidrule(lr){%d-%d} ", 
                                  col_counter, col_counter + n_graphs - 1))
    col_counter <- col_counter + n_graphs
    
    if (i < n_metrics) {
      header_line <- paste0(header_line, " & \\phantom{a} &")
      col_counter <- col_counter + 1
    }
  }
  header_line <- paste0(header_line, " \\\\\n")
  cat(header_line)
  cat(cmidrule_line, "\n")
  
  # Column headers (graph types)
  graph_header <- "$n$ & Method"
  for (i in 1:n_metrics) {
    for (graph in graph_order) {
      graph_header <- paste0(graph_header, " & ", graph)
    }
    if (i < n_metrics) {
      graph_header <- paste0(graph_header, " &")
    }
  }
  graph_header <- paste0(graph_header, " \\\\\n")
  cat(graph_header)
  cat("\\midrule\n")
  
  # Data rows
  for (n_val in n_order) {
    for (j in seq_along(method_order)) {
      method_display <- method_order[j]
      # Find original method name
      method_orig <- names(method_mapping)[method_mapping == method_display]
      if (length(method_orig) == 0) {
        method_orig <- method_display
      }
      
      # First column: n value (only for first method)
      if (j == 1) {
        cat(sprintf("%d & ", n_val))
      } else {
        cat(" & ")
      }
      
      # Method name
      cat(method_display)
      
      # For each metric
      for (metric in metrics) {
        cat(" & ")
        
        # For each graph type
        for (k in seq_along(graph_order)) {
          graph_display <- graph_order[k]
          graph_orig <- names(graph_mapping)[graph_mapping == graph_display]
          if (length(graph_orig) == 0) {
            graph_orig <- graph_display
          }
          
          # Get data row
          row_data <- df[df$n == n_val & 
                          df$method_name == method_orig & 
                          df$graph_type == graph_orig, ]
          
          # Get mean and sd column names
          # Handle special cases for Time and Success Rate metrics
          if (metric == "Time") {
            mean_col <- "time_mean"
            sd_col <- "time_sd"
          } else if (metric == "Success Rate") {
            mean_col <- "success_rate"
            sd_col <- NULL  # Success Rate doesn't have SD
          } else {
            mean_col <- paste0(metric, "_mean")
            sd_col <- paste0(metric, "_sd")
          }
          
          if (nrow(row_data) > 0 && mean_col %in% names(row_data)) {
            mean_val <- row_data[[mean_col]][1]
            
            if (!is.na(mean_val) && !is.null(mean_val)) {
              if (show_sd && !is.null(sd_col) && sd_col %in% names(row_data)) {
                sd_val <- row_data[[sd_col]][1]
                if (!is.na(sd_val) && !is.null(sd_val)) {
                  format_str <- sprintf("%%.%df (%%.%df)", digits, digits)
                  cat(sprintf(format_str, mean_val, sd_val))
                } else {
                  format_str <- sprintf("%%.%df", digits)
                  cat(sprintf(format_str, mean_val))
                }
              } else {
                format_str <- sprintf("%%.%df", digits)
                cat(sprintf(format_str, mean_val))
              }
            } else {
              cat("--")
            }
          } else {
            cat("--")
          }
          
          if (k < length(graph_order)) {
            cat(" & ")
          }
        }
        
        # Add separator between metrics
        if (metric != metrics[length(metrics)]) {
          cat(" &")
        }
      }
      
      cat(" \\\\\n")
    }
    
    # Add midrule between sample sizes (except after last)
    if (n_val != n_order[length(n_order)]) {
      cat("\\midrule\n")
    }
  }
  
  cat("\\bottomrule\n")
  cat("\\end{tabular}\n")
  cat("\\end{table}\n")
  if (landscape) {
    cat("\\end{landscape}\n")
  }
  cat("\n")
}
