# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

node_mse_vec_cpp <- function(X, K, eps = 1e-8) {
    .Call(`_DROP_node_mse_vec_cpp`, X, K, eps)
}

update_k_cpp <- function(X, K, lambda, tol = 1e-4, max_iter = 1000L) {
    .Call(`_DROP_update_k_cpp`, X, K, lambda, tol, max_iter)
}

calculate_ebic_cpp <- function(K, X, gamma = 0.5) {
    .Call(`_DROP_calculate_ebic_cpp`, K, X, gamma)
}

